**4.1 Exercise on Functions:**

Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [1]:
def convert_units(conversion_type, value):
    """
    Convert units based on the selected conversion type.

    Parameters:
    conversion_type (str): The type of conversion selected by the user.
    value (float): The numeric value to convert.

    Returns:
    float: The converted value.
    """

    if conversion_type == "1":
        # meters to feet
        return value * 3.28084
    elif conversion_type == "2":
        # feet to meters
        return value / 3.28084
    elif conversion_type == "3":
        # kilograms to pounds
        return value * 2.20462
    elif conversion_type == "4":
        # pounds to kilograms
        return value / 2.20462
    elif conversion_type == "5":
        # liters to gallons
        return value * 0.264172
    elif conversion_type == "6":
        # gallons to liters
        return value / 0.264172
    else:
        return None


def main():
    print("Unit Conversion Program")
    print("------------------------")
    print("Choose conversion type:")
    print("1. Meters (m) to Feet (ft)")
    print("2. Feet (ft) to Meters (m)")
    print("3. Kilograms (kg) to Pounds (lbs)")
    print("4. Pounds (lbs) to Kilograms (kg)")
    print("5. Liters (L) to Gallons (gal)")
    print("6. Gallons (gal) to Liters (L)")

    choice = input("Enter your choice (1-6): ")

    try:
        value = float(input("Enter the value to convert: "))

        result = convert_units(choice, value)

        if result is None:
            print("Error: Unsupported conversion type.")
        else:
            print(f"Converted value: {result:.4f}")

    except ValueError:
        print("Error: Please enter a valid numeric value.")


if __name__ == "__main__":
    main()

Unit Conversion Program
------------------------
Choose conversion type:
1. Meters (m) to Feet (ft)
2. Feet (ft) to Meters (m)
3. Kilograms (kg) to Pounds (lbs)
4. Pounds (lbs) to Kilograms (kg)
5. Liters (L) to Gallons (gal)
6. Gallons (gal) to Liters (L)
Enter your choice (1-6): 1
Enter the value to convert: 100
Converted value: 328.0840


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [2]:
def find_sum(numbers):
    """
    Calculate the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Calculate the average of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The average of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Find the maximum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The maximum number in the list.
    """
    return max(numbers)


def find_min(numbers):
    """
    Find the minimum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The minimum number in the list.
    """
    return min(numbers)


def main():
    print("Mathematical Operations on a List")
    print("----------------------------------")
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter your choice (1-4): ")

    try:
        user_input = input("Enter numbers separated by spaces: ")

        if not user_input.strip():
            raise ValueError("List cannot be empty.")

        numbers = list(map(float, user_input.split()))

        if choice == "1":
            result = find_sum(numbers)
            print("Sum:", result)

        elif choice == "2":
            result = find_average(numbers)
            print("Average:", result)

        elif choice == "3":
            result = find_max(numbers)
            print("Maximum:", result)

        elif choice == "4":
            result = find_min(numbers)
            print("Minimum:", result)

        else:
            print("Error: Invalid operation selected.")

    except ValueError:
        print("Error: Please enter valid numbers separated by spaces.")


if __name__ == "__main__":
    main()

Mathematical Operations on a List
----------------------------------
Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 4
Enter numbers separated by spaces: 3 6
Minimum: 3.0


**4.2 Exercise on List Manipulation:**

1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [3]:
def extract_every_other(lst):
    """
    Extract every other element from a list starting from the first element.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every other element from the original list.
    """
    return lst[::2]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)
print(result)

[1, 3, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [4]:
def get_sublist(lst, start, end):
    """
    Return a sublist from the given list between the start and end indices (inclusive).

    Parameters:
    lst (list): The original list.
    start (int): Starting index.
    end (int): Ending index.

    Returns:
    list: The sublist from start to end (inclusive).
    """
    return lst[start:end+1]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)
print(result)

[3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [5]:
def reverse_list(lst):
    """
    Reverse a list using slicing.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list with elements in reverse order.
    """
    return lst[::-1]


# Example
numbers = [1, 2, 3, 4, 5]
result = reverse_list(numbers)
print(result)

[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [6]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list using slicing.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list without the first and last elements.
    """
    return lst[1:-1]


# Example
numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)
print(result)

[2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [7]:
def get_first_n(lst, n):
    """
    Returns the first n elements from a list using slicing.

    Parameters:
    lst (list): The input list.
    n (int): Number of elements to extract from the beginning.

    Returns:
    list: A list containing the first n elements.
    """
    return lst[:n]


# Example
numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 3)
print(result)

[1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [8]:
def get_last_n(lst, n):
    """
    Returns the last n elements from a list using slicing.

    Parameters:
    lst (list): The input list.
    n (int): Number of elements to extract from the end.

    Returns:
    list: A list containing the last n elements.
    """
    return lst[-n:]


# Example
numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)
print(result)

[4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [10]:
def reverse_skip(lst):
    """
    Returns every second element of a list in reverse order,
    starting from the second-to-last element.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every second element starting
    from the second-to-last element moving backward.
    """
    return lst[-2::-2]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)
print(result)

[5, 3, 1]


**4.3 Exercise on Nested List:**

1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [11]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
    lst (list): A nested list where each element may itself be a list.

    Returns:
    list: A single flattened list containing all elements.
    """
    flat_list = []
    for sublist in lst:
        for item in sublist:
            flat_list.append(item)
    return flat_list


# Example
nested_list = [[1, 2], [3, 4], [5]]
result = flatten(nested_list)
print(result)

[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [12]:
def access_nested_element(lst, indices):
    """
    Returns an element from a nested list using a list of indices.

    Parameters:
    lst (list): The nested list.
    indices (list): A list of indices that represent the position of the element.

    Returns:
    element: The element found at the specified nested position.
    """
    element = lst
    for index in indices:
        element = element[index]
    return element


# Example
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]

result = access_nested_element(lst, indices)
print(result)

6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [13]:
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list (any depth).

    Parameters:
    lst (list): A list that may contain numbers or other nested lists.

    Returns:
    int/float: The total sum of all numeric elements in the nested list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)   # recursion for nested lists
        else:
            total += item
    return total


# Example
nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print(result)

21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [14]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): A nested list that may contain other lists.
    elem (int/float/str): The element to remove.

    Returns:
    list: A modified nested list with the specified element removed.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))  # process nested list
        elif item != elem:
            result.append(item)
    return result


# Example
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2

result = remove_element(lst, elem)
print(result)

[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [15]:
def find_max(lst):
    """
    Finds the maximum element in a nested list regardless of depth.

    Parameters:
    lst (list): A nested list that may contain numbers or other lists.

    Returns:
    int/float: The maximum element in the nested list.
    """
    max_value = float('-inf')

    for item in lst:
        if isinstance(item, list):
            value = find_max(item)   # recursion for nested list
            if value > max_value:
                max_value = value
        else:
            if item > max_value:
                max_value = item

    return max_value


# Example
nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)
print(result)

6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [16]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
    lst (list): A nested list that may contain other lists.
    elem: The element to count in the list.

    Returns:
    int: The number of times the element appears in the nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # recursion for nested lists
        elif item == elem:
            count += 1
    return count


# Example
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2

result = count_occurrences(lst, elem)
print(result)

3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [17]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list.

    Parameters:
    lst (list): A list that may contain other nested lists.

    Returns:
    list: A flattened list containing all elements.
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))  # recursion for deeper lists
        else:
            result.append(item)

    return result


# Example
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [18]:
def average_nested(lst):
    """
    Calculates the average of all numbers in a nested list.

    Parameters:
    lst (list): A nested list that may contain numbers or other lists.

    Returns:
    float: The average of all elements in the nested list.
    """

    def helper(lst):
        total = 0
        count = 0
        for item in lst:
            if isinstance(item, list):
                t, c = helper(item)   # recursion
                total += t
                count += c
            else:
                total += item
                count += 1
        return total, count

    total, count = helper(lst)
    return total / count


# Example
nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)
print(result)

3.5


**10.1 Basic Vector and Matrix Operation with Numpy.**

Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}


In [29]:
import numpy as np
import time
import random

In [20]:
# 1. Initialize an empty array with size 2x2
arr1 = np.empty((2, 2))
print("Empty array (2x2):")
print(arr1)

# 2. Initialize an all one array with size 4x2
arr2 = np.ones((4, 2))
print("\nAll ones array (4x2):")
print(arr2)

# 3. Return a new array of given shape and type, filled with fill value
arr3 = np.full((3, 3), 7)   # shape 3x3 filled with 7
print("\nArray filled with value 7:")
print(arr3)

# 4. Return a new array of zeros with same shape and type as a given array
arr4 = np.zeros_like(arr2)
print("\nZeros array like arr2:")
print(arr4)

# 5. Return a new array of ones with same shape and type as a given array
arr5 = np.ones_like(arr4)
print("\nOnes array like arr4:")
print(arr5)

# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
arr6 = np.array(new_list)
print("\nNumpy array from list:")
print(arr6)

Empty array (2x2):
[[1.01036575e-315 0.00000000e+000]
 [6.45626409e-186 2.68789399e-317]]

All ones array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with value 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros array like arr2:
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Ones array like arr4:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Numpy array from list:
[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [21]:
# 1. Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("1.", arr1)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n2.\n", arr2)

# 3. Create a 3x3 identity matrix
arr3 = np.eye(3)
print("\n3.\n", arr3)

# 4. Create a random array of size 30 and find the mean
arr4 = np.random.random(30)
print("\n4. Mean:", arr4.mean())

# 5. Create a 10x10 array with random values and find min and max
arr5 = np.random.random((10, 10))
print("\n5. Min:", arr5.min(), "Max:", arr5.max())

# 6. Create a zero array of size 10 and replace 5th element with 1
arr6 = np.zeros(10)
arr6[4] = 1
print("\n6.", arr6)

# 7. Reverse an array
arr7 = np.array([1,2,0,0,4,0])
print("\n7.", arr7[::-1])

# 8. Create a 2D array with 1 on border and 0 inside
arr8 = np.ones((5,5))
arr8[1:-1,1:-1] = 0
print("\n8.\n", arr8)

# 9. Create an 8x8 checkerboard matrix
arr9 = np.zeros((8,8), dtype=int)
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print("\n9.\n", arr9)

1. [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2.
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3.
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean: 0.474012410058767

5. Min: 9.916422733635688e-05 Max: 0.9917092279744738

6. [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. [0 4 0 0 2 1]

8.
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9.
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [23]:
# Given arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# 1. Add the two arrays
print("Addition:")
print(x + y)

# 2. Subtract the two arrays
print("\nSubtraction:")
print(x - y)

# 3. Multiply the array with an integer
print("\nMultiply x by 3:")
print(x * 3)

# 4. Square of each element
print("\nSquare of elements of x:")
print(x ** 2)

# 5. Dot product
print("\nDot product v and w:")
print(np.dot(v, w))

print("\nDot product x and v:")
print(np.dot(x, v))

print("\nDot product x and y:")
print(np.dot(x, y))

# 6. Concatenate
print("\nConcatenate x and y along rows:")
print(np.concatenate((x, y), axis=0))

print("\nConcatenate v and w along column:")
print(np.vstack((v, w)).T)

# 7. Concatenate x and v
print("\nTrying to concatenate x and v:")
print(np.concatenate((x, v)))

Addition:
[[ 6  8]
 [10 13]]

Subtraction:
[[-4 -4]
 [-4 -3]]

Multiply x by 3:
[[ 3  6]
 [ 9 15]]

Square of elements of x:
[[ 1  4]
 [ 9 25]]

Dot product v and w:
219

Dot product x and v:
[29 77]

Dot product x and y:
[[19 22]
 [50 58]]

Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along column:
[[ 9 11]
 [10 12]]

Trying to concatenate x and v:


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

The error occurs because x is a 2-dimensional array (2×2) while v is a 1-dimensional array (size 2). NumPy requires arrays to have the same number of dimensions for concatenation. Therefore, v must be reshaped into a 2D array using reshape() before concatenation.

Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1
= I.
2. Prove AB ̸= BA.
3. Prove (AB)T
= BT AT
.
• Solve the following system of Linear equation using Inverse Methods.
2x−3y + z =−1
x−y + 2z =−3
3x + y−z = 9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX= B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [24]:
# Given matrices
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
result1 = np.dot(A, A_inv)

print("A inverse:")
print(A_inv)

print("\nA * A^-1:")
print(result1)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nAB:")
print(AB)

print("\nBA:")
print(BA)

# 3. Prove (AB)^T = B^T A^T
left = (AB).T
right = np.dot(B.T, A.T)

print("\n(AB)^T:")
print(left)

print("\nB^T A^T:")
print(right)

# -------------------------------------------------
# Solve system of linear equations using matrix form
# 2x − 3y + z = -1
# x − y + 2z = -3
# 3x + y − z = 9

A_eq = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])

B_eq = np.array([-1,-3,9])

# Using inverse method
A_eq_inv = np.linalg.inv(A_eq)

X = np.dot(A_eq_inv, B_eq)

print("\nSolution [x,y,z]:")
print(X)

A inverse:
[[-2.    1.  ]
 [ 1.75 -0.75]]

A * A^-1:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

(AB)^T:
[[23 51]
 [13 29]]

B^T A^T:
[[23 51]
 [13 29]]

Solution [x,y,z]:
[ 2.  1. -2.]


**10.2 Experiment: How Fast is Numpy?**

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [25]:
# Create two Python lists of size 1,000,000
list1 = list(range(1000000))
list2 = list(range(1000000))

# Measure time for Python list addition
start = time.time()

result_list = [list1[i] + list2[i] for i in range(len(list1))]

end = time.time()

print("Time taken using Python Lists:", end - start, "seconds")


# Convert lists to NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

# Measure time for NumPy array addition
start = time.time()

result_array = arr1 + arr2

end = time.time()

print("Time taken using NumPy Arrays:", end - start, "seconds")

Time taken using Python Lists: 0.08225727081298828 seconds
Time taken using NumPy Arrays: 0.0021047592163085938 seconds


2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [26]:
# Create two Python lists of size 1,000,000
list1 = list(range(1000000))
list2 = list(range(1000000))

# Measure time for Python list multiplication
start = time.time()

result_list = [list1[i] * list2[i] for i in range(len(list1))]

end = time.time()

print("Time taken using Python Lists:", end - start, "seconds")


# Convert lists to NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

# Measure time for NumPy array multiplication
start = time.time()

result_array = arr1 * arr2

end = time.time()

print("Time taken using NumPy Arrays:", end - start, "seconds")

Time taken using Python Lists: 0.08169031143188477 seconds
Time taken using NumPy Arrays: 0.002881288528442383 seconds


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [27]:
# Create two Python lists of size 1,000,000
list1 = list(range(1000000))
list2 = list(range(1000000))

# Dot product using Python lists
start = time.time()

dot_product = sum(list1[i] * list2[i] for i in range(len(list1)))

end = time.time()

print("Dot product using Python Lists:", dot_product)
print("Time taken using Python Lists:", end - start, "seconds")


# Convert lists to NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

# Dot product using NumPy
start = time.time()

dot_product_np = np.dot(arr1, arr2)

end = time.time()

print("\nDot product using NumPy:", dot_product_np)
print("Time taken using NumPy Arrays:", end - start, "seconds")

Dot product using Python Lists: 333332833333500000
Time taken using Python Lists: 0.06245589256286621 seconds

Dot product using NumPy: 333332833333500000
Time taken using NumPy Arrays: 0.0009567737579345703 seconds


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.
• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [30]:
# Create two 1000x1000 matrices using Python lists
size = 1000

A = [[random.random() for _ in range(size)] for _ in range(size)]
B = [[random.random() for _ in range(size)] for _ in range(size)]

# Matrix multiplication using Python lists
start = time.time()

result = [[0]*size for _ in range(size)]

for i in range(size):
    for j in range(size):
        for k in range(size):
            result[i][j] += A[i][k] * B[k][j]

end = time.time()

print("Time taken using Python Lists:", end - start, "seconds")


# Matrix multiplication using NumPy
A_np = np.array(A)
B_np = np.array(B)

start = time.time()

result_np = np.dot(A_np, B_np)

end = time.time()

print("Time taken using NumPy Arrays:", end - start, "seconds")

Time taken using Python Lists: 200.7860369682312 seconds
Time taken using NumPy Arrays: 0.06479763984680176 seconds
